# Generated by Django 6.0.4 on 2026-05-05 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0002_category_alter_audiocontent_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadHabitProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('habit_type', models.CharField(max_length=50)),
                ('program_length_days', models.PositiveIntegerField()),
                ('has_medical_risk', models.BooleanField(default=False)),
                ('crisis_resource_url', models.URLField(blank=True)),
                ('savings_unit', models.CharField(blank=True, max_length=50)),
                ('savings_per_day', models.FloatField(default=0)),
                ('savings_money_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calories_per_unit', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'motivation_programs',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_slip_at', models.DateField(blank=True, null=True)),
                ('slip_count', models.PositiveIntegerField(default=0)),
                ('replacement_habit_id', models.UUIDField(blank=True, null=True)),
                ('triggers_captured', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='motivation.badhabitprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'motivation_enrollments',
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.CreateModel(
            name='UrgeSOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('breathing_completed', models.BooleanField(default=False)),
                ('audio_played', models.BooleanField(default=False)),
                ('accountability_message_sent', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_activations', to='motivation.userenrollment')),
            ],
            options={
                'db_table': 'motivation_urge_sos',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuitReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quit_reasons', to='motivation.userenrollment')),
            ],
            options={
                'db_table': 'motivation_quit_reasons',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalMotivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to='motivation/personal/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_motivations', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_motivations', to='motivation.userenrollment')),
            ],
            options={
                'db_table': 'motivation_personal_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('emotion', 'Emotion'), ('location', 'Location'), ('time', 'Time'), ('person', 'Person'), ('situation', 'Situation')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='motivation.userenrollment')),
            ],
            options={
                'db_table': 'motivation_triggers',
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('reflection_prompt', models.TextField()),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_days', to='insights.audiocontent')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='motivation.badhabitprogram')),
            ],
            options={
                'db_table': 'motivation_program_days',
                'ordering': ['day_number'],
                'unique_together': {('program', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='DayCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task_done', models.BooleanField(default=True)),
                ('reflection_response', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='motivation.userenrollment')),
            ],
            options={
                'db_table': 'motivation_day_completions',
                'unique_together': {('enrollment', 'day_number')},
            },
        ),
    ]
