# Generated by Django 6.0.4 on 2026-05-05 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Fitness', 'Fitness'), ('Mindfulness', 'Mindfulness'), ('Productivity', 'Productivity'), ('Learning', 'Learning'), ('Finance', 'Finance'), ('Relationships', 'Relationships'), ('Other', 'Other')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('color_hex', models.CharField(default='#4F46E5', max_length=7)),
                ('frequency_type', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('n_per_week', 'N Per Week')], max_length=20)),
                ('frequency_days', models.JSONField(default=list)),
                ('frequency_count', models.PositiveIntegerField(default=1)),
                ('quantity_target', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=40)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('time_window_start', models.TimeField(blank=True, null=True)),
                ('time_window_end', models.TimeField(blank=True, null=True)),
                ('identity_tags', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium')], default='small', max_length=20)),
                ('reminder_times', models.JSONField(default=list)),
                ('is_quit_habit', models.BooleanField(default=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('streak_freezes_available', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchored_habits', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreakEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('freeze_used', 'Freeze Used'), ('freeze_earned', 'Freeze Earned'), ('streak_broken', 'Streak Broken'), ('streak_started', 'Streak Started'), ('milestone', 'Milestone')], max_length=20)),
                ('event_date', models.DateField()),
                ('streak_value', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_events', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streak_events',
            },
        ),
        migrations.CreateModel(
            name='VacationPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacation_periods',
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('completed_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto_health', 'Auto Health'), ('widget', 'Widget'), ('watch', 'Watch'), ('shortcut', 'Shortcut')], default='manual', max_length=20)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('streak_freeze_used', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_completions',
                'unique_together': {('habit', 'completion_date')},
            },
        ),
    ]
