# Generated by Django 6.0.4 on 2026-05-05 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('mindfulness', 'Mindfulness'), ('motivation', 'Motivation'), ('sleep', 'Sleep'), ('focus', 'Focus'), ('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('relationships', 'Relationships')], max_length=30)),
                ('audio_file', models.FileField(upload_to='insights/audio/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='insights/thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audio_content',
                'ordering': ['-published_at'],
            },
        ),
    ]
