# Generated by Django 6.0.4 on 2026-05-06 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_category_alter_audiocontent_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInsightInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_favorited', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='insights.audiocontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_insight_interactions',
                'unique_together': {('user', 'audio_content')},
            },
        ),
    ]
