# Generated by Django 6.0.4 on 2026-05-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_dataexport_export_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_attempts_window_start',
        ),
    ]
