# Generated by Django 6.0.4 on 2026-05-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Per-category notification toggles. Keys: habit_reminders, streak_risk, comeback, weekly_review, program_daily, marketing. Values: bool.'),
        ),
    ]
