# Generated by Django 6.0.4 on 2026-05-05 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('apple_calendar', 'Apple Calendar'), ('google_calendar', 'Google Calendar')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_blocks',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='WidgetSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('habits_today', models.JSONField(default=list)),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('momentum_index_7d', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'widget_snapshots',
            },
        ),
        migrations.CreateModel(
            name='HealthDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('apple_health', 'Apple Health'), ('google_fit', 'Google Fit')], max_length=20)),
                ('metric', models.CharField(choices=[('steps', 'Steps'), ('sleep_minutes', 'Sleep Minutes'), ('workout_minutes', 'Workout Minutes'), ('mindful_minutes', 'Mindful Minutes'), ('water_ml', 'Water (ml)'), ('weight_kg', 'Weight (kg)')], max_length=20)),
                ('value', models.FloatField()),
                ('recorded_date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_data_points',
                'ordering': ['-recorded_date'],
                'unique_together': {('user', 'source', 'metric', 'recorded_date')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('apple_calendar', 'Apple Calendar'), ('google_calendar', 'Google Calendar')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('data_categories', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_consents',
                'ordering': ['integration_type'],
                'unique_together': {('user', 'integration_type')},
            },
        ),
    ]
