# Generated by Django 6.0.4 on 2026-05-05 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('apple_product_id', models.CharField(blank=True, max_length=120)),
                ('google_product_id', models.CharField(blank=True, max_length=120)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['order', 'price_usd'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('provider', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255)),
                ('provider_receipt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('subscribed', 'Subscribed'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('refunded', 'Refunded'), ('manual_grant', 'Manual Grant')], max_length=30)),
                ('from_tier', models.CharField(blank=True, max_length=20)),
                ('to_tier', models.CharField(blank=True, max_length=20)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_event_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='subscriptions.usersubscription')),
            ],
            options={
                'db_table': 'subscription_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
