# Generated by Django 6.0.4 on 2026-05-05 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIArchetypeCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archetype_hash', models.CharField(max_length=64, unique=True)),
                ('mode', models.CharField(choices=[('starter', 'Starter'), ('expanded', 'Expanded')], max_length=10)),
                ('suggestions_json', models.JSONField()),
                ('prompt_version', models.CharField(default='v1', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_archetype_cache',
            },
        ),
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('single_select', 'Single Select'), ('multi_select', 'Multi Select'), ('scale', 'Scale'), ('free_text', 'Free Text')], max_length=20)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_progressive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'onboarding_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoachingReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposals', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=40)),
                ('frequency_type', models.CharField(default='daily', max_length=20)),
                ('quantity_target', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium')], default='tiny', max_length=10)),
                ('rationale', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('starter', 'Starter'), ('expanded', 'Expanded')], default='starter', max_length=10)),
                ('archetype_hash', models.CharField(blank=True, max_length=64)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_habit_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_suggestions',
            },
        ),
        migrations.CreateModel(
            name='NLModification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('habit_id', models.UUIDField()),
                ('instruction', models.TextField()),
                ('proposed_changes', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nl_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nl_modifications',
            },
        ),
        migrations.CreateModel(
            name='UserAIProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('archetype_hash', models.CharField(blank=True, max_length=64)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('health_flags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ai_profiles',
            },
        ),
    ]
