# Generated by Django 6.0.4 on 2026-05-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiarchetypecache',
            name='archetype_hash',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
